In [1]:
'''
【课程1.3】  Numpy通用函数

基本操作

'''

'\n【课程1.3】  Numpy通用函数\n\n基本操作\n\n'

In [2]:
import numpy as np

In [7]:
# 数组形状：.T/.reshape()/.resize()

ar1 = np.arange(10)
ar2 = np.ones((5,2))

# T方法：转置，例如原shape为(3,4)/(2,3,4)，转置结果为(4,3)/(4,3,2) → 所以一维数组转置后结果不变
print(ar1,'\n',ar1.T)
print(ar2,'\n',ar2.T)

ar3 = ar1.reshape(2,5)                         # 改变已有数组的维度
ar4 = np.zeros((4,6)).reshape(3,8)             # 生成后可以直接改变数组形状
ar5 = np.reshape(np.arange(12),(3,4))          # 参数内部添加数组,目标形状
print(ar1,'\n',ar3)
print(ar4)
print(ar5)
print('-------')

ar6 = np.resize(np.arange(5),(3,4))             # 返回指定形状的新数组,如有必要就会重复填充新值
print(ar6)                                      # .T/.reshape()/.resize()都是生成新的数组

[0 1 2 3 4 5 6 7 8 9] 
 [0 1 2 3 4 5 6 7 8 9]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[0 1 2 3 4 5 6 7 8 9] 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-------
[[0 1 2 3]
 [4 0 1 2]
 [3 4 0 1]]


In [11]:
# 数组的复制

# 类似python的list,向内存中生成的一个值 → 这里ar1和ar2指向同一个值，所以ar1改变，ar2一起改变
ar1 = np.arange(10)
ar2 = ar1
print(ar2 is ar1)
ar1[2] = 100
print(ar1,ar2)

# copy方法生成数组及其数据的完整拷贝.
ar3 = ar1.copy()
print(ar3 is ar1)
ar1[0] = 50
print(ar1,ar3)

True
[  0   1 100   3   4   5   6   7   8   9] [  0   1 100   3   4   5   6   7   8   9]
False
[ 50   1 100   3   4   5   6   7   8   9] [  0   1 100   3   4   5   6   7   8   9]


In [13]:
# 数组类型转换：.astype()

# 在参数位置来设置数组中元素的类型
ar1 = np.arange(10,dtype=np.float)
print(ar1,ar1.dtype)
print('-------')

# astype()转换数组中元素的数据类型
# 数组类型用np.int32，而不是直接int32
ar2 = ar1.astype(np.int32)
print(ar1,ar1.dtype)
print(ar2,ar2.dtype)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] float64
-------
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] float64
[0 1 2 3 4 5 6 7 8 9] int32


In [20]:
# 数组堆叠

a = np.arange(5)                        # a是一维数组,5个元素
b = np.arange(5,9)                      # b是一维数组,4个元素
ar1 = np.hstack((a,b))                  # numpy.hstack(tup)：水平（按列顺序）堆叠数组
print(a,a.shape)
print(b,b.shape)
print(ar1,ar1.shape)

a = np.array([[1],[2],[3]])             # a是二维数组,3个元素
b = np.array([['a'],['b'],['c']])       # b是二维数组,3个元素
ar2 = np.hstack((a,b))
print(a,a.shape)
print(b,b.shape)
print(ar2,ar2.shape)                     

a = np.arange(5) 
b = np.arange(5,10)
ar1 = np.vstack((a,b))                  # numpy.vstack(tup)：垂直（按列顺序）堆叠数组
print(a,a.shape)
print(b,b.shape)
print(ar1,ar1.shape)
a = np.array([[1],[2],[3]])            
b = np.array([['a'],['b'],['c'],['d']])       
ar2 = np.vstack((a,b))
print(a,a.shape)
print(b,b.shape)
print(ar2,ar2.shape)    

a = np.arange(5) 
b = np.arange(5,10)
ar1 = np.stack((a,b))                   # numpy.stack(arrays, axis=0)：沿着新轴连接数组的序列，形状必须一样
ar2 = np.stack((a,b),axis=1)            # axis表示按照什么样的形式进行堆叠,假设有2个数组[1 2 3]和[4 5 6]，shape均为(3,0)
print(a,a.shape)                        # axis=0：[[1 2 3] [4 5 6]]，shape为(2,3)
print(b,b.shape)                        # axis=1：[[1 4] [2 5] [3 6]]，shape为(3,2)
print(ar1,ar1.shape)  
print(ar2,ar2.shape)  

[0 1 2 3 4] (5,)
[5 6 7 8] (4,)
[0 1 2 3 4 5 6 7 8] (9,)
[[1]
 [2]
 [3]] (3, 1)
[['a']
 ['b']
 ['c']] (3, 1)
[['1' 'a']
 ['2' 'b']
 ['3' 'c']] (3, 2)
[0 1 2 3 4] (5,)
[5 6 7 8 9] (5,)
[[0 1 2 3 4]
 [5 6 7 8 9]] (2, 5)
[[1]
 [2]
 [3]] (3, 1)
[['a']
 ['b']
 ['c']
 ['d']] (4, 1)
[['1']
 ['2']
 ['3']
 ['a']
 ['b']
 ['c']
 ['d']] (7, 1)
[0 1 2 3 4] (5,)
[5 6 7 8 9] (5,)
[[0 1 2 3 4]
 [5 6 7 8 9]] (2, 5)
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]] (5, 2)


In [22]:
# 数组拆分 
ar = np.arange(16).reshape(4,4)
ar1 = np.hsplit(ar,2)              # numpy.hsplit(ary, indices_or_sections)：将数组水平（逐列）拆分为多个子数组 → 按列拆分
print(ar)
print(ar1,type(ar1))               # 输出结果为列表，列表中元素为数组

ar2 = np.vsplit(ar,4)
print(ar2,type(ar2))               # numpy.vsplit(ary, indices_or_sections)：:将数组垂直（行方向）拆分为多个子数组 → 按行拆

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])] <class 'list'>
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])] <class 'list'>


In [25]:
# 数组简单运算

ar = np.arange(6).reshape(2,3)
print(ar + 10)                                      # 加法
print(ar * 2)                                       # 乘法
print(1 / (ar + 1))                                 # 除法
print(ar ** 0.5)                                    # 乘方

print(ar.mean())                                    # 平均值
print(ar.max())                                     # 最大值
print(ar.min())                                     # 最小值
print(ar.std())                                     # 标准差
print(ar.var())                                     # 方差
print(ar.sum(),np.sum(ar,axis=0))                   # 求和，np.sum() → axis为0，按列求和；axis为1，按行求和
print(np.sort(np.array([1,4,3,2,5,6])))             # 排序

[[10 11 12]
 [13 14 15]]
[[ 0  2  4]
 [ 6  8 10]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[0.         1.         1.41421356]
 [1.73205081 2.         2.23606798]]
2.5
5
0
1.707825127659933
2.9166666666666665
15 [3 5 7]
[1 2 3 4 5 6]


	作业1：创建一个20个元素的数组，分别改变成两个形状：(4,5),(5,6) （提示：超出范围用resize）

	作业2：创建一个(4,4)的数组，把其元素类型改为字符型

	作业3：根据要求创建数组，运用数组的运算方法得到结果：result = ar * 10 +100，并求出result的均值及求和

In [28]:
# 1
ar = np.arange(20)
ar1 = ar.reshape(4,5)
ar2 = np.resize(ar,(5,6))
print(ar)
print(ar1)
print(ar2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19  0  1  2  3]
 [ 4  5  6  7  8  9]]


In [31]:
# 2
ar = np.arange(16,dtype=np.int).reshape((4,4))
ar1 = ar.astype(np.str)
print(ar1)

[['0' '1' '2' '3']
 ['4' '5' '6' '7']
 ['8' '9' '10' '11']
 ['12' '13' '14' '15']]


In [34]:
# 3
ar = np.arange(16,dtype=np.int).reshape((4,4))
result = ar * 10 + 100
print(result)
print(result.mean())
print(result.sum(),np.sum(result,axis=0),np.sum(result,axis=1))

[[100 110 120 130]
 [140 150 160 170]
 [180 190 200 210]
 [220 230 240 250]]
175.0
2800 [640 680 720 760] [460 620 780 940]
