In [1]:
'''
【课程1.2】  Numpy基础数据结构

NumPy数组是一个多维数组对象，称为ndarray。其由两部分组成：
① 实际的数据
② 描述这些数据的元数据

'''

In [9]:
import numpy as np

# 多维数组ndarray

ar = np.array([1,2,3,4,5,6,7,8,9])
print(ar)               # 输出数组，注意数组的格式：中括号，元素之间没有逗号（和列表区分）
print(ar.ndim)          # 输出数组维度的个数（轴数），或者说“秩”，维度的数量也称rank
print(ar.shape)         # 输出数组的维度,对于n行m列的数组,shape为(n,m)
print(ar.size)          # 数组的元素总数，对于n行m列的数组，元素总数为n*m
print(ar.dtype)         # 数组中元素的类型，类似type()（注意了，type()是函数，.dtype是方法）
print(ar.itemsize)      # 数组中每个元素的字节大小，int32类型字节为4，float64的字节为8
print(ar.data)          # 包含实际数组元素的缓冲区，由于一般通过数组的索引获取元素，所以通常不需要使用这个属性。
ar                      # 交互方式下输出，会有array(数组)

'''
 数组的基本属性
 ① 数组的维数称为秩（rank），一维数组的秩为1，二维数组的秩为2，以此类推
 ② 在NumPy中，每一个线性的数组称为是一个轴（axes），秩其实是描述轴的数量：
 比如说，二维数组相当于是两个一维数组，其中第一个一维数组中每个元素又是一个一维数组
 所以一维数组就是NumPy中的轴（axes），第一个轴相当于是底层数组，第二个轴是底层数组里的数组。
 而轴的数量——秩，就是数组的维数。 

'''

[1 2 3 4 5 6 7 8 9]
1
(9,)
9
int32
4


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
# 创建数组：array()函数，括号内可以是列表、元祖、数组、生成器等

ar1 = np.array(range(10))                   # 整型
ar2 = np.array([1,2,3.14,5,6])              # 浮点型
ar3 = np.array([[1,2,3],['a','b','c']])     # 二维数组
ar4 = np.array([[1,2,3],['a','b','c','d']]) # 如果数据不对称,矩阵的秩会改变

print(ar1,type(ar1),ar1.dtype)
print(ar2,type(ar2),ar2.dtype)
print(ar3,ar3.shape,ar3.ndim,ar3.size)      # 二维数组,一共6个元素
print(ar4,ar4.shape,ar4.ndim,ar4.size)      # 一维数组,一共2个元素

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'> int32
[1.   2.   3.14 5.   6.  ] <class 'numpy.ndarray'> float64
[['1' '2' '3']
 ['a' 'b' 'c']] (2, 3) 2 6
[list([1, 2, 3]) list(['a', 'b', 'c', 'd'])] (2,) 1 2


In [11]:
# 创建数组：arange()，类似range()，在给定间隔内返回均匀间隔的值。

print(np.arange(10))               # 返回0-9,整型
print(np.arange(10.0))             # 返回0-9,浮点型
print(np.arange(5,13))             # 返回5-12,整型
print(np.arange(5.0,13.0,2))       # 返回5-12,浮点型,步长为2
print(np.arange(100000))           # 如果数组太大而无法打印，NumPy会自动跳过数组的中心部分，并只打印边角：

[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 5  6  7  8  9 10 11 12]
[ 5.  7.  9. 11.]
[    0     1     2 ... 99997 99998 99999]


In [16]:
# 创建数组：linspace():返回在间隔[开始，停止]上计算的num个均匀间隔的样本。

ar1 = np.linspace(1,10,num=10)
ar2 = np.linspace(1,10,num=10,endpoint=False)   # endpoint去掉最后一个值
ar3 = np.linspace(1,10,num=10,retstep=True)     # retstep返回步长
print(ar1,type(ar1))
print(ar2,type(ar2))
print(ar3,type(ar3))

'''
 numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
 start：起始值，stop：结束值
 num：生成样本数，默认为50
 endpoint：如果为真，则停止是最后一个样本。否则，不包括在内。默认值为True。
 retstep：如果为真，返回（样本，步骤），其中步长是样本之间的间距 → 输出为一个包含2个元素的元祖，第一个元素为array，第二个为步长实际值

'''

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.] <class 'numpy.ndarray'>
[1.  1.9 2.8 3.7 4.6 5.5 6.4 7.3 8.2 9.1] <class 'numpy.ndarray'>
(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), 1.0) <class 'tuple'>


In [19]:
# 创建数组：zeros()/zeros_like()/ones()/ones_like()

ar1 = np.zeros(5)                         # 返回全是0的数组
ar2 = np.zeros((2,2),dtype=np.int)        # 可以指定数组形状和元素的数据类型
print(ar1,ar1.dtype)
print(ar2,ar2.dtype)
'''
 numpy.zeros(shape, dtype=float, order='C'):返回给定形状和类型的新数组，用零填充。
 shape：数组纬度，二维以上需要用()，且输入参数为整数
 dtype：数据类型，默认numpy.float64
 order：是否在存储器中以C或Fortran连续（按行或列方式）存储多维数据。
'''

ar3 = np.array([list(range(5)),list(range(5,10))])
ar4 = np.zeros_like(ar3)                   # 返回具有与给定数组相同的形状和类型的零数组，这里ar4根据ar3的形状和dtype创建一个全0的数组
print(ar3,ar3.dtype)
print(ar4,ar4.dtype)

ar5 = np.ones(9)
ar6 = np.ones((2,3,4))
ar7 = np.ones_like(ar3)
print(ar5,ar5.dtype)
print(ar6,ar6.dtype)
print(ar7,ar7.dtype)

[0. 0. 0. 0. 0.] float64
[[0 0]
 [0 0]] int32
[[0 1 2 3 4]
 [5 6 7 8 9]] int32
[[0 0 0 0 0]
 [0 0 0 0 0]] int32
[1. 1. 1. 1. 1. 1. 1. 1. 1.] float64
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]] float64
[[1 1 1 1 1]
 [1 1 1 1 1]] int32


In [20]:
# 创建数组：eye()

print(np.eye(5)) # 创建一个正方的N*N的单位矩阵，对角线值为1，其余为0

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
作业1：分别按照要求，生成一个一维数组、二维数组，并且查看其shape

作业2：生成一个一维数组，起始值为5，终点值为15，样本数为10个
 
作业3：按照要求创建以下数组
 


In [25]:
# 1
a1 = np.array([1,2,'a','hello',[1,2,3],{'two':200,'one':100}])
print(a1.shape)

a2 = np.array([['0','1','2','3','4','5'],
               ['a','b','c','d','e','f'],
               ['True','False','True','False','True','True']]
             )
print(a2.shape)

(6,)
(3, 6)


In [31]:
# 2

a3 = np.linspace(5,14,num=10)
print(a3)

[ 5.  6.  7.  8.  9. 10. 11. 12. 13. 14.]


In [40]:
# 3
a4 = np.zeros((4,4),dtype=np.float)
print(a4)

a5 = np.ones((2,3),dtype=np.float)
print(a5)

a6 = np.eye(3,dtype=np.int)
print(a6)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
