In [ ]:
'''
【课程2.5】  Pandas数据结构Dataframe：基本概念及创建

"二维数组"Dataframe：是一个表格型的数据结构，包含一组有序的列，其列的值类型可以是数值、字符串、布尔值等。

Dataframe中的数据以一个或多个二维块存放，不是列表、字典或一维数组结构。

'''

In [8]:
import numpy as np
import pandas as pd

In [7]:
# Dataframe 数据结构
# Dataframe是一个表格型的数据结构，“带有标签的二维数组”。
# Dataframe带有index（行标签）和columns（列标签）

data = {'name':['Jack','Tom','Alice'],
        'age':[23,24,25],
        'gender':['m','m','f']}
frame = pd.DataFrame(data)
print(frame)
print(type(frame))
print(frame.index,f'\n该数据类型是:{type(frame.index)}')
print(frame.columns,f'\n该数据类型是:{type(frame.columns)}')
print(frame.values,f'\n该数据类型是:{type(frame.values)}')

'''
 查看数据，数据类型为dataframe
 .index查看行标签
 .columns查看列标签
 .values查看值，数据类型为ndarray
'''

    name  age gender
0   Jack   23      m
1    Tom   24      m
2  Alice   25      f
<class 'pandas.core.frame.DataFrame'>
RangeIndex(start=0, stop=3, step=1) 
该数据类型是:<class 'pandas.core.indexes.range.RangeIndex'>
Index(['name', 'age', 'gender'], dtype='object') 
该数据类型是:<class 'pandas.core.indexes.base.Index'>
[['Jack' 23 'm']
 ['Tom' 24 'm']
 ['Alice' 25 'f']] 
该数据类型是:<class 'numpy.ndarray'>


In [13]:
# Dataframe 创建方法一：由数组/list组成的字典
# 创建方法:pandas.Dataframe()

data1 = {
    'a':[1,2,3],
    'b':[3,4,5],
    'c':[5,6,7]
}
data2 = {'one':np.random.rand(3),
         'two':np.random.rand(3)}
print(data1)
print(data2)

df1 = pd.DataFrame(data1)             # 由数组/list组成的字典 创建Dataframe，columns为字典key，index为默认数字标签
df2 = pd.DataFrame(data2)             # 字典的值的长度必须保持一致

print(df1)
print(df2)

df1 = pd.DataFrame(data1,columns=['b','c','a','d']) # columns参数：可以重新指定列的顺序，格式为list，如果现有数据中没有该列（比如'd'），则产生NaN值
print(df1)
df2 = pd.DataFrame(data1,columns=['b','c'])         # 如果columns重新指定时候，列的数量可以少于原数据
print(df2)

df2 = pd.DataFrame(data2,index=['f1','f2','f3'])    # index参数：重新定义index，格式为list，长度必须保持一致
print(df2)

{'a': [1, 2, 3], 'b': [3, 4, 5], 'c': [5, 6, 7]}
{'one': array([0.15952154, 0.72002228, 0.3421577 ]), 'two': array([0.17376482, 0.59372166, 0.56777493])}
   a  b  c
0  1  3  5
1  2  4  6
2  3  5  7
        one       two
0  0.159522  0.173765
1  0.720022  0.593722
2  0.342158  0.567775
   b  c  a    d
0  3  5  1  NaN
1  4  6  2  NaN
2  5  7  3  NaN
   b  c
0  3  5
1  4  6
2  5  7
         one       two
f1  0.159522  0.173765
f2  0.720022  0.593722
f3  0.342158  0.567775


In [14]:
# Dataframe 创建方法二：由Series组成的字典

data1 = {'one':pd.Series(np.random.rand(2)),                                      # 没有设置index的Series
         'two':pd.Series(np.random.rand(3))}

data2 = {'one':pd.Series(np.random.rand(2),index=['a','b']),                      # 设置index的Series
         'two':pd.Series(np.random.rand(3),index=['a','b','c'])}

print(data1)
print(data2)

df1 = pd.DataFrame(data1)  # 由Seris组成的字典 创建Dataframe，columns为字典key，index为Series的标签（如果Series没有指定标签，则是默认数字标签）           
df2 = pd.DataFrame(data2)  # Series可以长度不一样，生成的Dataframe会出现NaN值

print(df1)
print(df2)



{'one': 0    0.441779
1    0.292909
dtype: float64, 'two': 0    0.577493
1    0.589455
2    0.062039
dtype: float64}
{'one': a    0.412221
b    0.158195
dtype: float64, 'two': a    0.011613
b    0.438659
c    0.513564
dtype: float64}
        one       two
0  0.441779  0.577493
1  0.292909  0.589455
2       NaN  0.062039
        one       two
a  0.412221  0.011613
b  0.158195  0.438659
c       NaN  0.513564


In [19]:
# Dataframe 创建方法三：通过二维数组直接创建

ar = np.random.rand(9).reshape(3,3)
print(ar)
df1 = pd.DataFrame(ar)                                                    # 通过二维数组直接创建Dataframe，得到一样形状的结果数据，如果不指定index和columns，两者均返回默认数字格式
df2 = pd.DataFrame(ar,index=['a','b','c'],columns=['one','two','three'])  # index和colunms指定长度与原数组保持一致
print(df1)                      
print(df2)

[[0.0534642  0.27963767 0.84071368]
 [0.36385315 0.58337928 0.33826202]
 [0.3417927  0.15710704 0.37571708]]
          0         1         2
0  0.053464  0.279638  0.840714
1  0.363853  0.583379  0.338262
2  0.341793  0.157107  0.375717
        one       two     three
a  0.053464  0.279638  0.840714
b  0.363853  0.583379  0.338262
c  0.341793  0.157107  0.375717


In [21]:
# Dataframe 创建方法四：由字典组成的列表

data = [{'one':1,'two':2},
        {'one':5,'two':10,'three':20}]
print(data)
df1 = pd.DataFrame(data)
df2 = pd.DataFrame(data,index=['a','b'])           
df3 = pd.DataFrame(data,columns=['one','two'])     # 由字典组成的列表创建Dataframe，columns为字典的key，index不做指定则为默认数组标签
print(df1)                                         # colunms和index参数分别重新指定相应列及行标签
print(df2)
print(df3)

[{'one': 1, 'two': 2}, {'one': 5, 'two': 10, 'three': 20}]
   one  three  two
0    1    NaN    2
1    5   20.0   10
   one  three  two
a    1    NaN    2
b    5   20.0   10
   one  two
0    1    2
1    5   10


In [29]:
# Dataframe 创建方法五：由字典组成的字典

data = {'Jack':{'math':90,'english':89,'art':78},
       'Marry':{'math':82,'english':95,'art':92},
       'Tom':{'math':78,'english':67}}
df1 = pd.DataFrame(data)                               # 由字典组成的字典创建Dataframe，columns为字典的key，index为子字典的key
print(df1)

df2 = pd.DataFrame(data,columns=['Jack','Tom','Bob'])  # columns参数可以增加和减少现有列，如出现新的列，值为NaN

print(df2)                                             # index在这里和之前不同，并不能改变原有index，如果指向新的标签，值为NaN


         Jack  Marry   Tom
art        78     92   NaN
english    89     95  67.0
math       90     82  78.0
         Jack   Tom  Bob
art        78   NaN  NaN
english    89  67.0  NaN
math       90  78.0  NaN


作业1：用四种不同的方法，创建以下Dataframe（保证columns和index一致，值不做要求）

In [38]:
df1 = pd.DataFrame(
    {'four':[4,5,6,7,8],
     'one':[1,2,3,4,5],
     'three':[3,4,5,6,7],
     'two':[2,3,4,5,6]},
    index=['a','b','c','d','e']
)
df2 = pd.DataFrame(
    {
        'one':pd.Series([1,2,3,4,5],index=list('abcde')),
        'two':pd.Series([2,3,4,5,6],index=list('abcde')),
        'three':pd.Series([3,4,5,6,7],index=list('abcde')),
        'four':pd.Series([4,5,6,7,8],index=list('abcde')),
    }
)

df3 = pd.DataFrame(np.arange(20).reshape(5,4),index=list('abcde'),columns=['one','two','three','four'])

df4 = pd.DataFrame([
    {'one':1,'two':2,'three':3,'four':4},
    {'one':2,'two':3,'three':4,'four':5},
    {'one':3,'two':4,'three':5,'four':6},
    {'one':4,'two':5,'three':6,'four':7},
    {'one':5,'two':6,'three':7,'four':8},
],index=list('abcde'))

print(df1)
print(df2)
print(df3)
print(df4)

   four  one  three  two
a     4    1      3    2
b     5    2      4    3
c     6    3      5    4
d     7    4      6    5
e     8    5      7    6
   one  two  three  four
a    1    2      3     4
b    2    3      4     5
c    3    4      5     6
d    4    5      6     7
e    5    6      7     8
   one  two  three  four
a    0    1      2     3
b    4    5      6     7
c    8    9     10    11
d   12   13     14    15
e   16   17     18    19
   four  one  three  two
a     4    1      3    2
b     5    2      4    3
c     6    3      5    4
d     7    4      6    5
e     8    5      7    6
