In [ ]:
'''
【课程1.6】  Numpy数据的输入输出

numpy读取/写入数组数据、文本数据

'''

In [2]:
import numpy as np

In [4]:
# 存储数组数据 .npy文件

import os
os.chdir(r'D:\user_profile\python')

ar = np.random.rand(5,5)
print(ar)
np.save('arraydata.npy',ar)

[[0.03345752 0.98704777 0.05589934 0.89298751 0.62797244]
 [0.13390943 0.4764105  0.08056207 0.60272845 0.98491185]
 [0.83349608 0.62722893 0.15286671 0.59988915 0.25886288]
 [0.11299974 0.6076214  0.68465745 0.02146056 0.12285964]
 [0.92562851 0.34791903 0.06614385 0.41942627 0.64323142]]


In [5]:
# 读取数组数据 .npy文件

ar_load = np.load('arraydata.npy')
print(ar_load)

[[0.03345752 0.98704777 0.05589934 0.89298751 0.62797244]
 [0.13390943 0.4764105  0.08056207 0.60272845 0.98491185]
 [0.83349608 0.62722893 0.15286671 0.59988915 0.25886288]
 [0.11299974 0.6076214  0.68465745 0.02146056 0.12285964]
 [0.92562851 0.34791903 0.06614385 0.41942627 0.64323142]]


In [8]:
# 存储/读取文本文件

ar = np.random.rand(5,5)
np.savetxt('array.txt',ar,delimiter=',',fmt='%.2f')                # savetxt方法存储为文本txt文件,delimiter指定分隔符,fmt指定格式

ar_loadtxt = np.loadtxt('array.txt',delimiter=',')
print(ar_loadtxt)

[[0.04 0.89 0.48 0.54 0.37]
 [0.38 0.75 0.38 0.42 0.95]
 [0.   0.01 0.53 0.26 0.15]
 [0.84 0.47 0.22 0.3  0.61]
 [0.16 0.15 0.68 0.38 0.09]]


In [ ]:
	作业1：创建一个10*10的整数随机数组，取值范围为0-100，并存为txt文件，用逗号分开	

In [15]:
ar = np.random.randint(100,size=(10,10))

np.savetxt('arr.txt',ar,delimiter=',',fmt='%i')
ar_load = np.loadtxt('arr.txt',delimiter=',')
print(ar_load)

[[29. 38. 68. 75. 15.  9.  7. 27. 50. 43.]
 [45. 52. 77. 51. 38. 51. 60. 40. 62. 65.]
 [24. 10.  9. 69. 39. 98.  3. 41. 46. 58.]
 [86. 53. 92. 58. 25. 68. 39.  2. 23. 18.]
 [21. 16. 33. 43. 23. 14. 79. 76. 39.  3.]
 [50.  3. 17. 84. 97. 58. 83. 73. 10. 42.]
 [71. 66. 67. 46. 29. 59. 98. 25. 46. 42.]
 [34. 33. 53. 31. 72. 77.  7. 65. 68. 11.]
 [31.  6. 15.  4. 65. 79. 29. 33. 72. 32.]
 [55. 56. 33. 84. 33. 60. 24. 69. 33. 12.]]
