'''
【课程1.4】  Numpy索引及切片

核心：基本索引及切片 / 布尔型索引及切片

'''

In [2]:
import numpy as np

In [13]:
# 基本索引及切片

ar = np.arange(20)

# 一维数组切片
print(ar)
print(ar[4])
print(ar[3:6])

# 二维数组切片
ar = np.arange(16).reshape(4,4)
print(ar,f'数组的轴数为{ar.ndim}')                             # 4 * 4 的二维数组
print(ar[2],f'数组的轴数为{ar[2].ndim}')                       # 切片为下一维度的一个元素，所以是一维数组
print(ar[2][1])                                                # 二次索引，得到一维数组中的一个值
print(ar[1:3],f'数组的轴数为{ar[1:3].ndim}')                   # 切片为两个一维数组组成的二维数组
print(ar[2,2])                                                 # 元素为第三行,第三列
print(ar[:2,1:])                                               # 切片数组中的1,2行、2,3,4列 → 二维数组

# 三维数组切片
ar = np.arange(8).reshape(2,2,2)
print(ar,f'数组的轴数为{ar.ndim}')                             # 2 * 2 * 2 的三维数组
print(ar[0],f'数组的轴数为{ar[0].ndim}')                       # 三维数组的下一个维度的第一个元素 → 一个二维数组
print(ar[0][0],f'数组的轴数为{ar[0][0].ndim}')                 # 三维数组的下一个维度的第一个元素下的第一个元素 → 一个一维数组
print(ar[0][0][1],f'数组的轴数为{ar[0][0][1].ndim}')           #  取到具体的值 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
4
[3 4 5]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 数组的轴数为2
[ 8  9 10 11] 数组的轴数为1
9
[[ 4  5  6  7]
 [ 8  9 10 11]] 数组的轴数为2
10
[[1 2 3]
 [5 6 7]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]] 数组的轴数为3
[[0 1]
 [2 3]] 数组的轴数为2
[0 1] 数组的轴数为1
1 数组的轴数为0


In [16]:
# 布尔型索引及切片

ar = np.arange(12).reshape(3,4)
i = np.array([True,False,True])            # 布尔型索引,以布尔型的矩阵去筛选元素
j = np.array([True,True,False,False])
print(ar)
print(i)
print(j)
                                            
print(ar[i,:])                              # 在第一维度做判断，只保留True，这里第一维度就是行，ar[i,:] = ar[i]（简单书写格式）
print(ar[:,j])                              # 在第二维度做判断，这里如果ar[:,i]会有警告，因为i是3个元素，而ar在列上有4个

m = ar > 5
print(m)                                    # m是一个判断矩阵
print(ar[m])                                # 用m判断矩阵去筛选ar数组中>5的元素

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ True False  True]
[ True  True False False]
[[ 0  1  2  3]
 [ 8  9 10 11]]
[[0 1]
 [4 5]
 [8 9]]
[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]
[ 6  7  8  9 10 11]


In [18]:
# 数组索引及切片的值更改、复制

ar = np.arange(10)
print(ar)
ar[5] = 100
ar[7:9] = 200
print(ar)                            # 一个标量赋值给一个索引/切片时，会自动改变/传播原始数组

ar = np.arange(10)
b = ar.copy()                        # 复制                        
b[7:9] = 200
print(ar)                          
print(b)

[0 1 2 3 4 5 6 7 8 9]
[  0   1   2   3   4 100   6 200 200   9]
[0 1 2 3 4 5 6 7 8 9]
[  0   1   2   3   4   5   6 200 200   9]


In [ ]:
	作业1：按照要求创建数组，通过索引，其ar[4]、ar[:2,3:]、ar[3][2]分别是多少

	作业2：按照要求创建数组，筛选出元素值大于5的值并生成新的数组

In [23]:
ar = np.arange(25,dtype=np.int).reshape(5,5)

print(ar)
print(ar[4])
print(ar[:2,3:])
print(ar[3][2])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[20 21 22 23 24]
[[3 4]
 [8 9]]
17


In [24]:
ar = np.arange(10,dtype=np.int).reshape(2,5)
result = ar[ar>5]
print(result)

[6 7 8 9]
